const c=document.getElementById('particles'),x=c.getContext('2d');let ps=[];
function rs(){const d=devicePixelRatio||1;c.width=innerWidth*d;c.height=innerHeight*d;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';x.setTransform(d,0,0,d,0,0);ps=Array.from({length:Math.min(70,innerWidth/18)},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.3+.25,v:Math.random()*.2+.04}))}
function ap(){x.clearRect(0,0,innerWidth,innerHeight);x.fillStyle='rgba(255,255,255,.22)';ps.forEach(p=>{p.y-=p.v;if(p.y<0)p.y=innerHeight;x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fill()});requestAnimationFrame(ap)}addEventListener('resize',rs);rs();ap();
document.getElementById('menu').onclick=()=>document.getElementById('nav').classList.toggle('open');
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('show')),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));
let counted=false;const co=new IntersectionObserver(([e])=>{if(!e.isIntersecting||counted)return;counted=true;document.querySelectorAll('[data-count]').forEach(el=>{let t=+el.dataset.count,s=performance.now();function f(n){let p=Math.min((n-s)/1300,1),v=Math.floor(t*(1-Math.pow(1-p,3)));el.textContent=v+(t>=1000?'+':'');if(p<1)requestAnimationFrame(f)}requestAnimationFrame(f)})},{threshold:.5});co.observe(document.querySelector('.stats'));
function bars(el){for(let i=0;i<24;i++){let b=document.createElement('i');b.style.height=(5+Math.random()*25)+'px';el.appendChild(b)}}document.querySelectorAll('.mini-wave').forEach(bars);
let ac,osc,gain,playing=false,timer,progress=0;
function tone(button,progressBar){if(playing){osc?.stop();playing=false;clearInterval(timer);document.querySelectorAll('.play,.main-play,.preview-btn').forEach(b=>b.textContent=b.classList.contains('preview-btn')?'▶ Preview':'▶');return}ac=ac||new(window.AudioContext||window.webkitAudioContext)();osc=ac.createOscillator();gain=ac.createGain();osc.type='sine';osc.frequency.value=82+Math.random()*180;gain.gain.setValueAtTime(.0001,ac.currentTime);gain.gain.exponentialRampToValueAtTime(.05,ac.currentTime+.12);gain.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+5);osc.connect(gain).connect(ac.destination);osc.start();osc.stop(ac.currentTime+5);playing=true;button.textContent='❚❚';progress=0;if(progressBar){timer=setInterval(()=>{progress+=2;progressBar.style.width=progress+'%';if(progress>=100){clearInterval(timer);playing=false;button.textContent='▶';progressBar.style.width='0'}},100)}osc.onended=()=>{playing=false;button.textContent=button.classList.contains('preview-btn')?'▶ Preview':'▶'}}
document.querySelector('.main-play').onclick=e=>tone(e.currentTarget,document.querySelector('.progress i'));document.querySelectorAll('.play,.preview-btn').forEach(b=>b.onclick=e=>tone(e.currentTarget));
const w=document.querySelector('.wave'),wc=w.getContext('2d');function rw(){let d=devicePixelRatio||1;w.width=w.clientWidth*d;w.height=w.clientHeight*d;wc.setTransform(d,0,0,d,0,0)}rw();addEventListener('resize',rw);function dw(t=0){let W=w.clientWidth,H=w.clientHeight;wc.clearRect(0,0,W,H);wc.strokeStyle='rgba(255,255,255,.65)';wc.lineWidth=1.4;wc.beginPath();for(let i=0;i<W;i++){let y=H/2+Math.sin(i*.045+t*.003)*11+Math.sin(i*.014+t*.0017)*18;i?wc.lineTo(i,y):wc.moveTo(i,y)}wc.stroke();requestAnimationFrame(dw)}dw();